### ISSUE TITLE
Sintáxis/Código

### ISSUE THREAD

**Issue by lucasjaviluna** [victoria-peinado/Desarrollo-Gesti-n-de-Publicidad#1]
[Low]
    - Hay muchos console.log
	- Esto se podría evitar poniendo una clase del lado del css y usando esa clase en el botón https://vscode.dev/github/victoria-peinado/Desarrollo-Gesti-n-de-Publicidad/blob/main/Front/Radio/src/app/block/block.component.html#L26
	- Hay una mezcla de español - inglés en los nombres de las variables y métodos. Lo usual es escribir todo en inglés. Ej:
	https://vscode.dev/github/victoria-peinado/Desarrollo-Gesti-n-de-Publicidad/blob/main/Front/Radio/src/app/services/shared-data.service.ts#L15
	- Hay casos de archivos vacíos. Ej: https://vscode.dev/github/victoria-peinado/Desarrollo-Gesti-n-de-Publicidad/blob/main/Front/Radio/src/app/top-menu/top-menu.component.scss
	https://vscode.dev/github/victoria-peinado/Desarrollo-Gesti-n-de-Publicidad/blob/main/Front/Radio/src/app/orden-fecha/orden-fecha.component.scss
	- Este componente, si no lo usan borrenlo https://vscode.dev/github/victoria-peinado/Desarrollo-Gesti-n-de-Publicidad/blob/main/Front/Radio/src/app/dummy/dummy.component.ts

**Comment by victoria-peinado** [comment]
El issue @ #6  se a creado con el objetivo de pasar las cosas que estan hecas en español a ingles para evitar la mezcla.
