### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by lucasjaviluna** [victoria-peinado/Desarrollo-Gesti-n-de-Publicidad#3]
[Middle]
	- Esto se podría simplificar poniendo el template una sola vez y pasando la flag de true/false al input "lateral"
	https://vscode.dev/github/victoria-peinado/Desarrollo-Gesti-n-de-Publicidad/blob/main/Front/Radio/src/app/app.component.html#L2
	Algo como: 
	<div class="h-full">
	  <main-nav [lateral]="!isInicioRoute">
		<router-outlet></router-outlet>
	  </main-nav>
	</div>
	
	- Por qué crearon un componente dinámicamente en lugar de usarlo directamente en el template??
	https://vscode.dev/github/victoria-peinado/Desarrollo-Gesti-n-de-Publicidad/blob/main/Front/Radio/src/app/orden-fecha/orden-fecha.component.ts#L12
	https://vscode.dev/github/victoria-peinado/Desarrollo-Gesti-n-de-Publicidad/blob/main/Front/Radio/src/app/nueva-orden/nueva-orden.component.ts#L51

**Comment by victoria-peinado** [comment]
Los componentes los creamos dinamicamente ya que es necesario segun nuentra logica de negocios.
https://vscode.dev/github/victoria-peinado/Desarrollo-Gesti-n-de-Publicidad/blob/main/Front/Radio/src/app/orden-fecha/orden-fecha.component.ts#L12
https://vscode.dev/github/victoria-peinado/Desarrollo-Gesti-n-de-Publicidad/blob/main/Front/Radio/src/app/nueva-orden/nueva-orden.component.ts#L51
