### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by lucasjaviluna** [victoria-peinado/Desarrollo-Gesti-n-de-Publicidad#5]
[Middle]
	Tendrían que usarse las path base url desde archivos de environment.
	https://vscode.dev/github/victoria-peinado/Desarrollo-Gesti-n-de-Publicidad/blob/main/Front/Radio/src/app/services/my-data.service.ts#L11

**Comment by victoria-peinado** [comment]
the commit d978f14db8e2af6a7a1fa8f59eaad244275b87e0 solved the issue...
